name = "tot"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "tot-db"
database_id = "85b7c382-a6f1-4bcc-8c57-86e4688d12ff"
